# Site settings
title: Lambda
email: lutianming1005 [at] hotmail.com
description: "Tianming的笔记"
baseurl: ""
url: "http://lutianming.github.io"
#twitter_username: jekyllrb
github_username:  lutianming

# Build settings
markdown: kramdown
permalink: pretty
